#!/usr/bin/with-contenv bash

# make our folders
#mkdir -p /config/.config/puddletag

# set webserver port on first install
#[[ ! -f /config/.config/puddletag/server-config.txt ]] && \
#  echo "port 8081" > /config/.config/puddletag/server-config.txt

# permissions
chown -R abc:abc \
	/config \
	/opt/puddletag
